# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('recieved_on', models.DateTimeField()),
                ('play_time', models.IntegerField()),
                ('altitude', models.IntegerField()),
                ('score', models.IntegerField()),
                ('ip', models.CharField(max_length=50)),
                ('registered_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BubbleUpServer.RegisteredClient')),
            ],
        ),
    ]
