# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BubbleUpServer', '0003_registeredclient_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredclient',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=40),
            preserve_default=False,
        ),
    ]
