# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BubbleUpServer', '0005_registeredclient_phrase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='ip',
        ),
    ]
