# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BubbleUpServer', '0006_remove_score_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user_name',
        ),
        migrations.AddField(
            model_name='registeredclient',
            name='user_name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
