# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BubbleUpServer', '0007_auto_20160512_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredclient',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='registeredclient',
            name='state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
